# Data Wrangling Project

In [1]:
import pandas as pd
import numpy as np

---

## 1- Inspecting the Data

In [2]:
df = pd.read_csv("Motor_Vehicle_Collisions_-_Crashes.csv")

C:\Users\DELL\AppData\Local\Temp\ipykernel_1732\2513209046.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Motor_Vehicle_Collisions_-_Crashes.csv")

In [3]:
print(f"The Shape of the dataframe: {df.shape}")

The Shape of the dataframe: (2196754, 29)

In [4]:
print(f"The Columns of the dataframe: {df.columns.tolist()}")

The Columns of the dataframe: ['CRASH DATE', 'CRASH TIME', 'BOROUGH', 'ZIP CODE', 'LATITUDE', 'LONGITUDE', 'LOCATION', 'ON STREET NAME', 'CROSS STREET NAME', 'OFF STREET NAME', 'NUMBER OF PERSONS INJURED', 'NUMBER OF PERSONS KILLED', 'NUMBER OF PEDESTRIANS INJURED', 'NUMBER OF PEDESTRIANS KILLED', 'NUMBER OF CYCLIST INJURED', 'NUMBER OF CYCLIST KILLED', 'NUMBER OF MOTORIST INJURED', 'NUMBER OF MOTORIST KILLED', 'CONTRIBUTING FACTOR VEHICLE 1', 'CONTRIBUTING FACTOR VEHICLE 2', 'CONTRIBUTING FACTOR VEHICLE 3', 'CONTRIBUTING FACTOR VEHICLE 4', 'CONTRIBUTING FACTOR VEHICLE 5', 'COLLISION_ID', 'VEHICLE TYPE CODE 1', 'VEHICLE TYPE CODE 2', 'VEHICLE TYPE CODE 3', 'VEHICLE TYPE CODE 4', 'VEHICLE TYPE CODE 5']

In [5]:
df.head() #A few sample rows of the dataframe

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,09/11/2021,2:39,NaN,NaN,NaN,NaN,NaN,WHITESTONE EXPRESSWAY,20 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4455765,Sedan,Sedan,NaN,NaN,NaN
1,03/26/2022,11:45,NaN,NaN,NaN,NaN,NaN,QUEENSBORO BRIDGE UPPER,NaN,NaN,...,NaN,NaN,NaN,NaN,4513547,Sedan,NaN,NaN,NaN,NaN
2,11/01/2023,1:29,BROOKLYN,11230.0,40.62179,-73.970024,"(40.62179, -73.970024)",OCEAN PARKWAY,AVENUE K,NaN,...,Unspecified,Unspecified,NaN,NaN,4675373,Moped,Sedan,Sedan,NaN,NaN
3,06/29/2022,6:55,NaN,NaN,NaN,NaN,NaN,THROGS NECK BRIDGE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4541903,Sedan,Pick-up Truck,NaN,NaN,NaN
4,09/21/2022,13:21,NaN,NaN,NaN,NaN,NaN,BROOKLYN BRIDGE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4566131,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN

In [6]:
df.info() #Information about the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2196754 entries, 0 to 2196753
Data columns (total 29 columns):
 #   Column                         Dtype
---  ------                         -----
 0   CRASH DATE                     object
 1   CRASH TIME                     object
 2   BOROUGH                        object
 3   ZIP CODE                       object
 4   LATITUDE                       float64
 5   LONGITUDE                      float64
 6   LOCATION                       object
 7   ON STREET NAME                 object
 8   CROSS STREET NAME              object
 9   OFF STREET NAME                object
 10  NUMBER OF PERSONS INJURED      float64
 11  NUMBER OF PERSONS KILLED       float64
 12  NUMBER OF PEDESTRIANS INJURED  int64
 13  NUMBER OF PEDESTRIANS KILLED   int64
 14  NUMBER OF CYCLIST INJURED      int64
 15  NUMBER OF CYCLIST KILLED       int64
 16  NUMBER OF MOTORIST INJURED     int64
 17  NUMBER OF MOTORIST KILLED      int64
 18  CONTRIBUTING FACTOR VEHICLE 1  object
 19  CONTRIBUTING FACTOR VEHICLE 2  object
 20  CONTRIBUTING FACTOR VEHICLE 3  object
 21  CONTRIBUTING FACTOR VEHICLE 4  object
 22  CONTRIBUTING FACTOR VEHICLE 5  object
 23  COLLISION_ID                   int64
 24  VEHICLE TYPE CODE 1            object
 25  VEHICLE TYPE CODE 2            object
 26  VEHICLE TYPE CODE 3            object
 27  VEHICLE TYPE CODE 4            object
 28  VEHICLE TYPE CODE 5            object
dtypes: float64(4), int64(7), object(18)
memory usage: 486.0+ MB

### Columns of the data frame:
 1.  CRASH DATE (Date) : The date of the Crash   
                   
 2.  CRASH TIME (Categorical) : The time of the Crash                      
 3.  BOROUGH (Categorical) : The administrative division of New York City where the crash occurred                         
 4.  ZIP CODE (Numerical) : The postal code of the neighborhood where the crash occurred                      
 5.  LATITUDE (Numerical) : The north-south position of the crash location                 
 6.  LONGITUDE (Numerical) : The east-west position of the crash location                     
 7.  LOCATION (Categorical) : The specific location where the crash occurred                   
 8.  ON STREET NAME (Categorical) : The name of the street where the crash occurred               
 9.  CROSS STREET NAME (Categorical) : The name of the cross street where the crash occurred               
 10. OFF STREET NAME (Categorical) : The name of the location if the crash happened off the street             
 11. NUMBER OF PERSONS INJURED (Numerical) : The total number of people who were injured in the crash    
 12. NUMBER OF PERSONS KILLED (Numerical) : The total number of people who were killed in the crash     
 13. NUMBER OF PEDESTRIANS INJURED (Numerical) : The number of pedestrians who were injured in the crash  
 14. NUMBER OF PEDESTRIANS KILLED (Numerical) : The number of pedestrians who were killed in the crash  
 15. NUMBER OF CYCLIST INJURED (Numerical) : The number of cyclists who were injured in the crash  
 16. NUMBER OF CYCLIST KILLED (Numerical) : The number of cyclists who were killed in the crash     
 17. NUMBER OF MOTORIST INJURED (Numerical) : The number of motorists (drivers/passengers) who were injured in the crash      
 18. NUMBER OF MOTORIST KILLED (Numerical) : The number of motorists (drivers/passengers) who were killed in the crash      
 19. CONTRIBUTING FACTOR VEHICLE 1 (Categorical) : The primary contributing factor for Vehicle 1 that caused the crash
 20. CONTRIBUTING FACTOR VEHICLE 2 (Categorical) : The primary contributing factor for Vehicle 2 that caused the crash 
 21. CONTRIBUTING FACTOR VEHICLE 3 (Categorical) : The primary contributing factor for Vehicle 3 that caused the crash 
 22. CONTRIBUTING FACTOR VEHICLE 4 (Categorical) : The primary contributing factor for Vehicle 4 that caused the crash 
 23. CONTRIBUTING FACTOR VEHICLE 5 (Categorical) : The primary contributing factor for Vehicle 5 that caused the crash
 24. COLLISION_ID (Numerical) : A unique identifier for each crash                     
 25. VEHICLE TYPE CODE 1 (Categorical) : The type of vehicle 1 involved in the crash           
 26. VEHICLE TYPE CODE 2 (Categorical) : The type of vehicle 1 involved in the crash           
 27. VEHICLE TYPE CODE 3 (Categorical) : The type of vehicle 1 involved in the crash          
 28. VEHICLE TYPE CODE 4 (Categorical) : The type of vehicle 1 involved in the crash          
 29. VEHICLE TYPE CODE 5 (Categorical) : The type of vehicle 1 involved in the crash

---

## 2- Handling Missing Values

In [7]:
# How many null values are in each column
df.isnull().sum()

CRASH DATE                             0
CRASH TIME                             0
BOROUGH                           675613
ZIP CODE                          675887
LATITUDE                          240157
LONGITUDE                         240157
LOCATION                          240157
ON STREET NAME                    476352
CROSS STREET NAME                 838902
OFF STREET NAME                  1812776
NUMBER OF PERSONS INJURED             18
NUMBER OF PERSONS KILLED              31
NUMBER OF PEDESTRIANS INJURED          0
NUMBER OF PEDESTRIANS KILLED           0
NUMBER OF CYCLIST INJURED              0
NUMBER OF CYCLIST KILLED               0
NUMBER OF MOTORIST INJURED             0
NUMBER OF MOTORIST KILLED              0
CONTRIBUTING FACTOR VEHICLE 1       7667
CONTRIBUTING FACTOR VEHICLE 2     350734
CONTRIBUTING FACTOR VEHICLE 3    2037979
CONTRIBUTING FACTOR VEHICLE 4    2160538
CONTRIBUTING FACTOR VEHICLE 5    2186842
COLLISION_ID                           0
VEHICLE TYPE CODE 1                15752
VEHICLE TYPE CODE 2               437504
VEHICLE TYPE CODE 3              2044099
VEHICLE TYPE CODE 4              2161842
VEHICLE TYPE CODE 5              2187150
dtype: int64

### Dropping rows with no location information for the crashes

In [8]:
# Looking for null values in location columns
df[
    (df["ON STREET NAME"].isnull() == True)
    & (df["OFF STREET NAME"].isnull() == True)
    & (df["CROSS STREET NAME"].isnull() == True)
    & (df["LOCATION"].isnull() == True)
    & (df["BOROUGH"].isnull() == True)
    & (df["ZIP CODE"].isnull() == True)
].count()

CRASH DATE                       30023
CRASH TIME                       30023
BOROUGH                              0
ZIP CODE                             0
LATITUDE                             0
LONGITUDE                            0
LOCATION                             0
ON STREET NAME                       0
CROSS STREET NAME                    0
OFF STREET NAME                      0
NUMBER OF PERSONS INJURED        30022
NUMBER OF PERSONS KILLED         30022
NUMBER OF PEDESTRIANS INJURED    30023
NUMBER OF PEDESTRIANS KILLED     30023
NUMBER OF CYCLIST INJURED        30023
NUMBER OF CYCLIST KILLED         30023
NUMBER OF MOTORIST INJURED       30023
NUMBER OF MOTORIST KILLED        30023
CONTRIBUTING FACTOR VEHICLE 1    29937
CONTRIBUTING FACTOR VEHICLE 2    27304
CONTRIBUTING FACTOR VEHICLE 3     3475
CONTRIBUTING FACTOR VEHICLE 4      699
CONTRIBUTING FACTOR VEHICLE 5      171
COLLISION_ID                     30023
VEHICLE TYPE CODE 1              29989
VEHICLE TYPE CODE 2              27529
VEHICLE TYPE CODE 3               3477
VEHICLE TYPE CODE 4                700
VEHICLE TYPE CODE 5                169
dtype: int64

In [9]:
# Taking indexes of rows with null values in location columns
indexes = df[
    (df["ON STREET NAME"].isnull() == True)
    & (df["OFF STREET NAME"].isnull() == True)
    & (df["CROSS STREET NAME"].isnull() == True)
    & (df["LOCATION"].isnull() == True)
    & (df["BOROUGH"].isnull() == True)
    & (df["ZIP CODE"].isnull() == True)
].index.tolist()

In [10]:
# Dropping rows with null values in location columns
df.drop(index=indexes,axis=0, inplace=True)

In [11]:
# After dropping rows with null values in location columns
df[
    (df["ON STREET NAME"].isnull() == True)
    & (df["OFF STREET NAME"].isnull() == True)
    & (df["CROSS STREET NAME"].isnull() == True)
    & (df["LOCATION"].isnull() == True)
    & (df["BOROUGH"].isnull() == True)
    & (df["ZIP CODE"].isnull() == True)
].count()

CRASH DATE                       0
CRASH TIME                       0
BOROUGH                          0
ZIP CODE                         0
LATITUDE                         0
LONGITUDE                        0
LOCATION                         0
ON STREET NAME                   0
CROSS STREET NAME                0
OFF STREET NAME                  0
NUMBER OF PERSONS INJURED        0
NUMBER OF PERSONS KILLED         0
NUMBER OF PEDESTRIANS INJURED    0
NUMBER OF PEDESTRIANS KILLED     0
NUMBER OF CYCLIST INJURED        0
NUMBER OF CYCLIST KILLED         0
NUMBER OF MOTORIST INJURED       0
NUMBER OF MOTORIST KILLED        0
CONTRIBUTING FACTOR VEHICLE 1    0
CONTRIBUTING FACTOR VEHICLE 2    0
CONTRIBUTING FACTOR VEHICLE 3    0
CONTRIBUTING FACTOR VEHICLE 4    0
CONTRIBUTING FACTOR VEHICLE 5    0
COLLISION_ID                     0
VEHICLE TYPE CODE 1              0
VEHICLE TYPE CODE 2              0
VEHICLE TYPE CODE 3              0
VEHICLE TYPE CODE 4              0
VEHICLE TYPE CODE 5              0
dtype: int64

In [12]:
# Dropping rows with unknown boroughs
df = df.dropna(subset=["BOROUGH"], ignore_index=True)

### Filling the rest of the missing values

In [13]:
df["NUMBER OF PERSONS INJURED"] = df["NUMBER OF PERSONS INJURED"].fillna(0)
df["NUMBER OF PERSONS KILLED"] = df["NUMBER OF PERSONS KILLED"].fillna(0)

In [14]:
df["CONTRIBUTING FACTOR VEHICLE 1"] = df["CONTRIBUTING FACTOR VEHICLE 1"].fillna(
    "Unknown"
)
df["CONTRIBUTING FACTOR VEHICLE 2"] = df["CONTRIBUTING FACTOR VEHICLE 2"].fillna(
    "Unknown"
)
df["CONTRIBUTING FACTOR VEHICLE 3"] = df["CONTRIBUTING FACTOR VEHICLE 3"].fillna(
    "Unknown"
)
df["CONTRIBUTING FACTOR VEHICLE 4"] = df["CONTRIBUTING FACTOR VEHICLE 4"].fillna(
    "Unknown"
)
df["CONTRIBUTING FACTOR VEHICLE 5"] = df["CONTRIBUTING FACTOR VEHICLE 5"].fillna(
    "Unknown"
)

In [15]:
df["LOCATION"] = df["LOCATION"].fillna("Unknown")
df["ON STREET NAME"] = df["ON STREET NAME"].fillna("Unknown")
df["OFF STREET NAME"] = df["OFF STREET NAME"].fillna("Unknown")
df["CROSS STREET NAME"] = df["CROSS STREET NAME"].fillna("Unknown")
df["ZIP CODE"] = df["ZIP CODE"].fillna("Unknown")
df["LONGITUDE"] = df["LONGITUDE"].fillna(0)
df["LATITUDE"] = df["LATITUDE"].fillna(0)

In [16]:
df["VEHICLE TYPE CODE 1"] = df["VEHICLE TYPE CODE 1"].fillna("Unknown")
df["VEHICLE TYPE CODE 2"] = df["VEHICLE TYPE CODE 2"].fillna("Unknown")
df["VEHICLE TYPE CODE 3"] = df["VEHICLE TYPE CODE 3"].fillna("Unknown")
df["VEHICLE TYPE CODE 4"] = df["VEHICLE TYPE CODE 4"].fillna("Unknown")
df["VEHICLE TYPE CODE 5"] = df["VEHICLE TYPE CODE 5"].fillna("Unknown")

In [17]:
df.isnull().sum()

CRASH DATE                       0
CRASH TIME                       0
BOROUGH                          0
ZIP CODE                         0
LATITUDE                         0
LONGITUDE                        0
LOCATION                         0
ON STREET NAME                   0
CROSS STREET NAME                0
OFF STREET NAME                  0
NUMBER OF PERSONS INJURED        0
NUMBER OF PERSONS KILLED         0
NUMBER OF PEDESTRIANS INJURED    0
NUMBER OF PEDESTRIANS KILLED     0
NUMBER OF CYCLIST INJURED        0
NUMBER OF CYCLIST KILLED         0
NUMBER OF MOTORIST INJURED       0
NUMBER OF MOTORIST KILLED        0
CONTRIBUTING FACTOR VEHICLE 1    0
CONTRIBUTING FACTOR VEHICLE 2    0
CONTRIBUTING FACTOR VEHICLE 3    0
CONTRIBUTING FACTOR VEHICLE 4    0
CONTRIBUTING FACTOR VEHICLE 5    0
COLLISION_ID                     0
VEHICLE TYPE CODE 1              0
VEHICLE TYPE CODE 2              0
VEHICLE TYPE CODE 3              0
VEHICLE TYPE CODE 4              0
VEHICLE TYPE CODE 5              0
dtype: int64

---

## 3-Correcting Data Types

In [18]:
df["CRASH DATE"] = pd.to_datetime(df["CRASH DATE"])
df["CRASH TIME"] = pd.to_datetime(df["CRASH TIME"]).dt.time

C:\Users\DELL\AppData\Local\Temp\ipykernel_1732\73599997.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["CRASH TIME"] = pd.to_datetime(df["CRASH TIME"]).dt.time

In [19]:
df.head()

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,2023-11-01,01:29:00,BROOKLYN,11230.0,40.621790,-73.970024,"(40.62179, -73.970024)",OCEAN PARKWAY,AVENUE K,Unknown,...,Unspecified,Unspecified,Unknown,Unknown,4675373,Moped,Sedan,Sedan,Unknown,Unknown
1,2021-09-11,09:35:00,BROOKLYN,11208.0,40.667202,-73.866500,"(40.667202, -73.8665)",Unknown,Unknown,1211 LORING AVENUE,...,Unknown,Unknown,Unknown,Unknown,4456314,Sedan,Unknown,Unknown,Unknown,Unknown
2,2021-12-14,08:13:00,BROOKLYN,11233.0,40.683304,-73.917274,"(40.683304, -73.917274)",SARATOGA AVENUE,DECATUR STREET,Unknown,...,Unknown,Unknown,Unknown,Unknown,4486609,Unknown,Unknown,Unknown,Unknown,Unknown
3,2021-12-14,08:17:00,BRONX,10475.0,40.868160,-73.831480,"(40.86816, -73.83148)",Unknown,Unknown,344 BAYCHESTER AVENUE,...,Unspecified,Unknown,Unknown,Unknown,4486660,Sedan,Sedan,Unknown,Unknown,Unknown
4,2021-12-14,21:10:00,BROOKLYN,11207.0,40.671720,-73.897100,"(40.67172, -73.8971)",Unknown,Unknown,2047 PITKIN AVENUE,...,Unspecified,Unknown,Unknown,Unknown,4487074,Sedan,Unknown,Unknown,Unknown,Unknown

In [20]:
df["NUMBER OF PERSONS INJURED"] = df["NUMBER OF PERSONS INJURED"].astype("Int64")
df["NUMBER OF PERSONS KILLED"] = df["NUMBER OF PERSONS KILLED"].astype("Int64")

In [21]:
df["BOROUGH"] = df["BOROUGH"].astype("string")
df["ZIP CODE"] = df["ZIP CODE"].astype("string")
df["LOCATION"] = df["LOCATION"].astype("string")
df["ON STREET NAME"] = df["ON STREET NAME"].astype("string")
df["OFF STREET NAME"] = df["OFF STREET NAME"].astype("string")
df["CROSS STREET NAME"] = df["CROSS STREET NAME"].astype("string")

In [22]:
df["CONTRIBUTING FACTOR VEHICLE 1"] = df["CONTRIBUTING FACTOR VEHICLE 1"].astype(
    "string"
)
df["CONTRIBUTING FACTOR VEHICLE 2"] = df["CONTRIBUTING FACTOR VEHICLE 2"].astype(
    "string"
)
df["CONTRIBUTING FACTOR VEHICLE 3"] = df["CONTRIBUTING FACTOR VEHICLE 3"].astype(
    "string"
)
df["CONTRIBUTING FACTOR VEHICLE 4"] = df["CONTRIBUTING FACTOR VEHICLE 4"].astype(
    "string"
)
df["CONTRIBUTING FACTOR VEHICLE 5"] = df["CONTRIBUTING FACTOR VEHICLE 5"].astype(
    "string"
)

In [23]:
df["VEHICLE TYPE CODE 1"] = df["VEHICLE TYPE CODE 1"].astype("string")
df["VEHICLE TYPE CODE 2"] = df["VEHICLE TYPE CODE 2"].astype("string")
df["VEHICLE TYPE CODE 3"] = df["VEHICLE TYPE CODE 3"].astype("string")
df["VEHICLE TYPE CODE 4"] = df["VEHICLE TYPE CODE 4"].astype("string")
df["VEHICLE TYPE CODE 5"] = df["VEHICLE TYPE CODE 5"].astype("string")

In [24]:
df.dtypes

CRASH DATE                       datetime64[ns]
CRASH TIME                               object
BOROUGH                          string[python]
ZIP CODE                         string[python]
LATITUDE                                float64
LONGITUDE                               float64
LOCATION                         string[python]
ON STREET NAME                   string[python]
CROSS STREET NAME                string[python]
OFF STREET NAME                  string[python]
NUMBER OF PERSONS INJURED                 Int64
NUMBER OF PERSONS KILLED                  Int64
NUMBER OF PEDESTRIANS INJURED             int64
NUMBER OF PEDESTRIANS KILLED              int64
NUMBER OF CYCLIST INJURED                 int64
NUMBER OF CYCLIST KILLED                  int64
NUMBER OF MOTORIST INJURED                int64
NUMBER OF MOTORIST KILLED                 int64
CONTRIBUTING FACTOR VEHICLE 1    string[python]
CONTRIBUTING FACTOR VEHICLE 2    string[python]
CONTRIBUTING FACTOR VEHICLE 3    string[python]
CONTRIBUTING FACTOR VEHICLE 4    string[python]
CONTRIBUTING FACTOR VEHICLE 5    string[python]
COLLISION_ID                              int64
VEHICLE TYPE CODE 1              string[python]
VEHICLE TYPE CODE 2              string[python]
VEHICLE TYPE CODE 3              string[python]
VEHICLE TYPE CODE 4              string[python]
VEHICLE TYPE CODE 5              string[python]
dtype: object

---

## 4- Cleaning Text/Categorical Data

In [25]:
df.head()

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,2023-11-01,01:29:00,BROOKLYN,11230.0,40.621790,-73.970024,"(40.62179, -73.970024)",OCEAN PARKWAY,AVENUE K,Unknown,...,Unspecified,Unspecified,Unknown,Unknown,4675373,Moped,Sedan,Sedan,Unknown,Unknown
1,2021-09-11,09:35:00,BROOKLYN,11208.0,40.667202,-73.866500,"(40.667202, -73.8665)",Unknown,Unknown,1211 LORING AVENUE,...,Unknown,Unknown,Unknown,Unknown,4456314,Sedan,Unknown,Unknown,Unknown,Unknown
2,2021-12-14,08:13:00,BROOKLYN,11233.0,40.683304,-73.917274,"(40.683304, -73.917274)",SARATOGA AVENUE,DECATUR STREET,Unknown,...,Unknown,Unknown,Unknown,Unknown,4486609,Unknown,Unknown,Unknown,Unknown,Unknown
3,2021-12-14,08:17:00,BRONX,10475.0,40.868160,-73.831480,"(40.86816, -73.83148)",Unknown,Unknown,344 BAYCHESTER AVENUE,...,Unspecified,Unknown,Unknown,Unknown,4486660,Sedan,Sedan,Unknown,Unknown,Unknown
4,2021-12-14,21:10:00,BROOKLYN,11207.0,40.671720,-73.897100,"(40.67172, -73.8971)",Unknown,Unknown,2047 PITKIN AVENUE,...,Unspecified,Unknown,Unknown,Unknown,4487074,Sedan,Unknown,Unknown,Unknown,Unknown

In [26]:
# Replacing Unspecified with Unknown
df["CONTRIBUTING FACTOR VEHICLE 1"] = df["CONTRIBUTING FACTOR VEHICLE 1"].replace("Unspecified","Unknown")
df["CONTRIBUTING FACTOR VEHICLE 2"] = df["CONTRIBUTING FACTOR VEHICLE 2"].replace("Unspecified","Unknown")
df["CONTRIBUTING FACTOR VEHICLE 3"] = df["CONTRIBUTING FACTOR VEHICLE 3"].replace("Unspecified","Unknown")
df["CONTRIBUTING FACTOR VEHICLE 4"] = df["CONTRIBUTING FACTOR VEHICLE 4"].replace("Unspecified","Unknown")
df["CONTRIBUTING FACTOR VEHICLE 5"] = df["CONTRIBUTING FACTOR VEHICLE 5"].replace("Unspecified","Unknown")

In [27]:
df["CONTRIBUTING FACTOR VEHICLE 2"].head(15)

0     Unknown
1     Unknown
2     Unknown
3     Unknown
4     Unknown
5     Unknown
6     Unknown
7     Unknown
8     Unknown
9     Unknown
10    Unknown
11    Unknown
12    Unknown
13    Unknown
14    Unknown
Name: CONTRIBUTING FACTOR VEHICLE 2, dtype: string

In [28]:
# Standardizing the values
df["BOROUGH"] = df["BOROUGH"].apply(str.strip)
df["BOROUGH"] = df["BOROUGH"].apply(str.title)
df["ZIP CODE"] = df["ZIP CODE"].apply(str.strip)
df["ZIP CODE"] = df["ZIP CODE"].apply(str.title)
df["LOCATION"] = df["LOCATION"].apply(str.strip)
df["LOCATION"] = df["LOCATION"].apply(str.title)
df["ON STREET NAME"] = df["ON STREET NAME"].apply(str.strip)
df["ON STREET NAME"] = df["ON STREET NAME"].apply(str.title)
df["CROSS STREET NAME"] = df["CROSS STREET NAME"].apply(str.strip)
df["CROSS STREET NAME"] = df["CROSS STREET NAME"].apply(str.title)
df["OFF STREET NAME"] = df["OFF STREET NAME"].apply(str.strip)
df["OFF STREET NAME"] = df["OFF STREET NAME"].apply(str.title)

In [29]:
df["CONTRIBUTING FACTOR VEHICLE 1"] = df["CONTRIBUTING FACTOR VEHICLE 1"].apply(
    str.strip
)
df["CONTRIBUTING FACTOR VEHICLE 1"] = df["CONTRIBUTING FACTOR VEHICLE 1"].apply(
    str.title
)
df["CONTRIBUTING FACTOR VEHICLE 2"] = df["CONTRIBUTING FACTOR VEHICLE 2"].apply(
    str.strip
)
df["CONTRIBUTING FACTOR VEHICLE 2"] = df["CONTRIBUTING FACTOR VEHICLE 2"].apply(
    str.title
)
df["CONTRIBUTING FACTOR VEHICLE 3"] = df["CONTRIBUTING FACTOR VEHICLE 3"].apply(
    str.strip
)
df["CONTRIBUTING FACTOR VEHICLE 3"] = df["CONTRIBUTING FACTOR VEHICLE 3"].apply(
    str.title
)
df["CONTRIBUTING FACTOR VEHICLE 4"] = df["CONTRIBUTING FACTOR VEHICLE 4"].apply(
    str.strip
)
df["CONTRIBUTING FACTOR VEHICLE 4"] = df["CONTRIBUTING FACTOR VEHICLE 4"].apply(
    str.title
)
df["CONTRIBUTING FACTOR VEHICLE 5"] = df["CONTRIBUTING FACTOR VEHICLE 5"].apply(
    str.strip
)
df["CONTRIBUTING FACTOR VEHICLE 5"] = df["CONTRIBUTING FACTOR VEHICLE 5"].apply(
    str.title
)

In [30]:
df["VEHICLE TYPE CODE 1"] = df["VEHICLE TYPE CODE 1"].apply(str.strip)
df["VEHICLE TYPE CODE 1"] = df["VEHICLE TYPE CODE 1"].apply(str.title)
df["VEHICLE TYPE CODE 2"] = df["VEHICLE TYPE CODE 2"].apply(str.strip)
df["VEHICLE TYPE CODE 2"] = df["VEHICLE TYPE CODE 2"].apply(str.title)
df["VEHICLE TYPE CODE 3"] = df["VEHICLE TYPE CODE 3"].apply(str.strip)
df["VEHICLE TYPE CODE 3"] = df["VEHICLE TYPE CODE 3"].apply(str.title)
df["VEHICLE TYPE CODE 4"] = df["VEHICLE TYPE CODE 4"].apply(str.strip)
df["VEHICLE TYPE CODE 4"] = df["VEHICLE TYPE CODE 4"].apply(str.title)
df["VEHICLE TYPE CODE 5"] = df["VEHICLE TYPE CODE 5"].apply(str.strip)
df["VEHICLE TYPE CODE 5"] = df["VEHICLE TYPE CODE 5"].apply(str.title)

In [31]:
df.head(10)

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,2023-11-01,01:29:00,Brooklyn,11230.0,40.621790,-73.970024,"(40.62179, -73.970024)",Ocean Parkway,Avenue K,Unknown,...,Unknown,Unknown,Unknown,Unknown,4675373,Moped,Sedan,Sedan,Unknown,Unknown
1,2021-09-11,09:35:00,Brooklyn,11208.0,40.667202,-73.866500,"(40.667202, -73.8665)",Unknown,Unknown,1211 Loring Avenue,...,Unknown,Unknown,Unknown,Unknown,4456314,Sedan,Unknown,Unknown,Unknown,Unknown
2,2021-12-14,08:13:00,Brooklyn,11233.0,40.683304,-73.917274,"(40.683304, -73.917274)",Saratoga Avenue,Decatur Street,Unknown,...,Unknown,Unknown,Unknown,Unknown,4486609,Unknown,Unknown,Unknown,Unknown,Unknown
3,2021-12-14,08:17:00,Bronx,10475.0,40.868160,-73.831480,"(40.86816, -73.83148)",Unknown,Unknown,344 Baychester Avenue,...,Unknown,Unknown,Unknown,Unknown,4486660,Sedan,Sedan,Unknown,Unknown,Unknown
4,2021-12-14,21:10:00,Brooklyn,11207.0,40.671720,-73.897100,"(40.67172, -73.8971)",Unknown,Unknown,2047 Pitkin Avenue,...,Unknown,Unknown,Unknown,Unknown,4487074,Sedan,Unknown,Unknown,Unknown,Unknown
5,2021-12-14,14:58:00,Manhattan,10017.0,40.751440,-73.973970,"(40.75144, -73.97397)",3 Avenue,East 43 Street,Unknown,...,Unknown,Unknown,Unknown,Unknown,4486519,Sedan,Station Wagon/Sport Utility Vehicle,Unknown,Unknown,Unknown
6,2021-12-14,16:50:00,Queens,11413.0,40.675884,-73.755770,"(40.675884, -73.75577)",Springfield Boulevard,East Gate Plaza,Unknown,...,Unknown,Unknown,Unknown,Unknown,4487127,Sedan,Station Wagon/Sport Utility Vehicle,Unknown,Unknown,Unknown
7,2021-12-14,23:10:00,Queens,11434.0,40.666840,-73.789410,"(40.66684, -73.78941)",North Conduit Avenue,150 Street,Unknown,...,Unknown,Unknown,Unknown,Unknown,4486635,Sedan,Sedan,Unknown,Unknown,Unknown
8,2021-12-14,17:58:00,Brooklyn,11217.0,40.681580,-73.974630,"(40.68158, -73.97463)",Unknown,Unknown,480 Dean Street,...,Unknown,Unknown,Unknown,Unknown,4486604,Tanker,Station Wagon/Sport Utility Vehicle,Unknown,Unknown,Unknown
9,2021-12-14,20:03:00,Brooklyn,11226.0,40.650680,-73.958810,"(40.65068, -73.95881)",Unknown,Unknown,878 Flatbush Avenue,...,Unknown,Unknown,Unknown,Unknown,4486991,Sedan,Unknown,Unknown,Unknown,Unknown

---

## 5- Filtering and Grouping Data

In [32]:
print(
    "The number of crashes in the year 2021 is:",
    df[df["CRASH DATE"].dt.year == 2021].size,
)

The number of crashes in the year 2021 is: 2094467

In [33]:
# Collisions in Manhattan
df[df["BOROUGH"] == "Manhattan"]

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
5,2021-12-14,14:58:00,Manhattan,10017.0,40.751440,-73.973970,"(40.75144, -73.97397)",3 Avenue,East 43 Street,Unknown,...,Unknown,Unknown,Unknown,Unknown,4486519,Sedan,Station Wagon/Sport Utility Vehicle,Unknown,Unknown,Unknown
11,2021-12-11,04:45:00,Manhattan,10001.0,40.748917,-73.993546,"(40.748917, -73.993546)",Unknown,Unknown,232 West 30 Street,...,Unknown,Unknown,Unknown,Unknown,4486905,Station Wagon/Sport Utility Vehicle,Unknown,Unknown,Unknown,Unknown
29,2022-04-24,15:35:00,Manhattan,10019.0,40.767242,-73.986206,"(40.767242, -73.986206)",West 56 Street,9 Avenue,Unknown,...,Unknown,Unknown,Unknown,Unknown,4521853,Station Wagon/Sport Utility Vehicle,Bike,Unknown,Unknown,Unknown
37,2022-04-07,14:14:00,Manhattan,10017.0,40.748158,-73.970330,"(40.748158, -73.97033)",1 Avenue,East 41 Street,Unknown,...,Passing Or Lane Usage Improper,Unknown,Unknown,Unknown,4522242,Sedan,Station Wagon/Sport Utility Vehicle,Unknown,Unknown,Unknown
41,2021-12-08,16:20:00,Manhattan,10128.0,40.776237,-73.943825,"(40.776237, -73.943825)",East End Avenue,East 88 Street,Unknown,...,Unknown,Unknown,Unknown,Unknown,4485234,Taxi,Station Wagon/Sport Utility Vehicle,Unknown,Unknown,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1521130,2025-08-05,08:05:00,Manhattan,10026.0,40.801655,-73.948370,"(40.801655, -73.94837)",Unknown,Unknown,45 W 116 St,...,Unknown,Unknown,Unknown,Unknown,4833350,Taxi,Sedan,Unknown,Unknown,Unknown
1521134,2025-08-04,13:19:00,Manhattan,10026.0,40.803158,-73.955055,"(40.803158, -73.955055)",Unknown,Unknown,266 W 115 St,...,Passing Or Lane Usage Improper,Unknown,Unknown,Unknown,4833343,Sedan,Station Wagon/Sport Utility Vehicle,Unknown,Unknown,Unknown
1521135,2025-08-05,08:30:00,Manhattan,10006.0,40.711033,-74.014534,"(40.711033, -74.014534)",Liberty St,West St,Unknown,...,Unknown,Unknown,Unknown,Unknown,4832972,Van,Unknown,Unknown,Unknown,Unknown
1521136,2025-07-31,13:22:00,Manhattan,10027.0,40.814910,-73.947945,"(40.81491, -73.947945)",Unknown,Unknown,2471 Frederick Douglass Blvd,...,Unknown,Unknown,Unknown,Unknown,4833410,Bike,Sedan,Unknown,Unknown,Unknown
1521137,2025-08-05,19:50:00,Manhattan,10001.0,40.747917,-73.991370,"(40.747917, -73.99137)",Unknown,Unknown,138 W 30 St,...,Unknown,Unknown,Unknown,Unknown,4833117,Sedan,Station Wagon/Sport Utility Vehicle,Unknown,Unknown,Unknown

About 300 thousands crashes out of 1.5 million happened in Manhattan

In [34]:
# People injured in crashes based of the borough it happened in
df.groupby("BOROUGH")["NUMBER OF PERSONS INJURED"].sum()

BOROUGH
Bronx             77442
Brooklyn         168999
Manhattan         75775
Queens           128688
Staten Island     19031
Name: NUMBER OF PERSONS INJURED, dtype: Int64

In [35]:
# People killed in crashes based of the borough it happened in
df.groupby("BOROUGH")["NUMBER OF PERSONS KILLED"].sum()

BOROUGH
Bronx            309
Brooklyn         704
Manhattan        374
Queens           574
Staten Island    106
Name: NUMBER OF PERSONS KILLED, dtype: Int64

In [36]:
# number of crashes for every day
df["CRASH YEAR"] = df["CRASH DATE"].dt.year
df.groupby("CRASH YEAR")["CRASH YEAR"].size()

CRASH YEAR
2012     77576
2013    155981
2014    156356
2015    163470
2016    153304
2017    142954
2018    149234
2019    137024
2020     73688
2021     72223
2022     68787
2023     65728
2024     65220
2025     39596
Name: CRASH YEAR, dtype: int64

In [37]:
# A pivot table showing the number of people injured in different boroughs every year
df.pivot_table(
    values="NUMBER OF PERSONS INJURED",
    index="BOROUGH",
    columns="CRASH YEAR",
    aggfunc=sum,
)

C:\Users\DELL\AppData\Local\Temp\ipykernel_1732\1444189382.py:2: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(

CRASH YEAR,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
BOROUGH,,,,,,,,,,,,,,
Bronx,2878,6259,5886,5626,6050,5844,6289,6528,5219,5757,5827,5811,6025,3443
Brooklyn,7526,15413,14247,13709,13452,12047,13198,13008,9699,11676,11512,12376,13150,7986
Manhattan,3868,7585,6909,6532,6236,5648,5435,5242,3576,4632,5132,5612,5779,3589
Queens,5506,10688,10033,10427,10928,10103,10818,11095,7269,8452,8517,9518,9939,5395
Staten Island,1245,2111,1577,1548,1484,1550,1340,1403,935,1095,1227,1366,1301,849

In [38]:
# A correlation matrix showing the correlation between people and pedestrians killed and injured
df_corr = df[["NUMBER OF PERSONS INJURED","NUMBER OF PERSONS KILLED","NUMBER OF PEDESTRIANS INJURED","NUMBER OF PEDESTRIANS KILLED"]]
df_corr.corr(numeric_only=True)

,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED
NUMBER OF PERSONS INJURED,1.000000,0.014926,0.314491,0.004989
NUMBER OF PERSONS KILLED,0.014926,1.000000,0.008950,0.738455
NUMBER OF PEDESTRIANS INJURED,0.314491,0.008950,1.000000,0.014439
NUMBER OF PEDESTRIANS KILLED,0.004989,0.738455,0.014439,1.000000

---

## 6- Statistical Summaries

In [39]:
print(f"The average rate of people injured in crashes is: {round(df["NUMBER OF PERSONS INJURED"].mean(),3)}")
print(f"The average rate of people killed in crashes is: {round(df["NUMBER OF PERSONS KILLED"].mean(),3)}")

The average rate of people injured in crashes is: 0.309
The average rate of people killed in crashes is: 0.001

In [40]:
print(f"The total number of people injured in crashes is: {df["NUMBER OF PERSONS INJURED"].sum()}")
print(f"The total number of people killed in crashes is: {df["NUMBER OF PERSONS KILLED"].sum()}")

The total number of people injured in crashes is: 469935
The total number of people killed in crashes is: 2067

In [41]:
print(f"The maximum number of people injured in a single crash is: {df["NUMBER OF PERSONS INJURED"].max()}")
print(f"The maximum number of people killed in a single crash is: {df["NUMBER OF PERSONS KILLED"].max()}")

The maximum number of people injured in a single crash is: 43
The maximum number of people killed in a single crash is: 8

In [42]:
max_borough = df["BOROUGH"].value_counts().idxmax()
print(f"The borough with the most crashes is {max_borough}")

The borough with the most crashes is Brooklyn

In [43]:
num_of_injuries = df[df["NUMBER OF PERSONS INJURED"] > 0].value_counts().count()
percentage = (num_of_injuries/df.shape[0]) * 100
print(f"The percentage of injured people in crashes is {round(percentage,2)}%")

The percentage of injured people in crashes is 23.48%

---

## 7- Exporting Raw and Cleaned Data

In [44]:
df.to_json("collisions_raw.json", orient="records", lines=True)

In [45]:
df.to_parquet('collisions_raw.parquet', engine="pyarrow")